spring:
  profiles:
    include: SECRET-KEY
  application:
    name: likelion
  datasource:
    url: jdbc:mysql://${database-host}:3306/${database-name} # Docker H2 서버 주소입니다.
    driver-class-name: com.mysql.cj.jdbc.Driver # H2 드라이버 클래스
    username: ${database-username} # 기본 사용자 이름
    password: ${database-password} # 기본 비밀번호
  h2:
    console:
      enabled: true # H2 콘솔을 활성화합니다.
      path: /h2-console # H2 콘솔의 접근 경로
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always # 애플리케이션 시작 시 스크립트 초기화 (기본값: embedded)

server:
  port: 8081